[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
test = "contracts/test"
script = "contracts/script"

# Optimizations
optimizer = true
optimizer_runs = 1000000
via_ir = false

# Solidity version
solc_version = "0.8.24"
evm_version = "cancun"

# Remappings
remappings = [
    "@openzeppelin/=contracts/lib/openzeppelin-contracts/",
    "account-abstraction/=contracts/lib/account-abstraction/",
    "forge-std/=contracts/lib/forge-std/src/"
]

# Gas reports
gas_reports = ["*"]

# Formatter
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

# Etherscan verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# RPC endpoints
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
