[profile.default]
src = "src"
test = "test.off"
script = "script"
out = "out"
libs = ["lib"]
cache_path = "cache"

# account-abstraction currently requires >=0.8.28
solc = "0.8.30"
optimizer = true
optimizer_runs = 200

remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "account-abstraction/=lib/account-abstraction/contracts/"
]
